# Generated by Django 5.0.7 on 2024-12-12 05:49

import django.core.validators
import django.db.models.deletion
import jewelstock.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='カテゴリーグループ')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='会社名')),
                ('address', models.CharField(max_length=200, verbose_name='所在地')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^[0-9]{10,11}$')], verbose_name='電話番号')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_date', models.DateField(blank=True, default=None, null=True, verbose_name='製造日')),
                ('sold_date', models.DateField(blank=True, default=None, null=True, verbose_name='売却日')),
            ],
        ),
        migrations.CreateModel(
            name='ModelNumber',
            fields=[
                ('model_number_id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^[0-9]{5}$')], verbose_name='型番')),
                ('name', models.CharField(max_length=20, verbose_name='形状名')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=200, verbose_name='作業')),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='形状名')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='取引形態')),
            ],
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='作業所名')),
                ('address', models.CharField(max_length=200, verbose_name='所在地')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^[0-9]{10,11}$')], verbose_name='電話番号')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='カテゴリー')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelstock.categorygroup', verbose_name='グループ')),
            ],
        ),
        migrations.CreateModel(
            name='ItemExistence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existence', models.BooleanField(default=False, verbose_name='店頭確認')),
                ('confirmed_date', models.DateTimeField(auto_now_add=True, verbose_name='確認日時')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelstock.item', verbose_name='単品')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='材料名')),
                ('stock', models.PositiveIntegerField(verbose_name='在庫数')),
                ('unit', models.CharField(max_length=10, verbose_name='単位')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelstock.company', verbose_name='仕入れ先')),
            ],
        ),
        migrations.CreateModel(
            name='ItemMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='個数')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelstock.item', verbose_name='単品')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelstock.material', verbose_name='材料')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_material',
            field=models.ManyToManyField(through='jewelstock.ItemMaterial', to='jewelstock.material', verbose_name='材料'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_code', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^[0-9]{14}$')], verbose_name='商品コード')),
                ('name', models.CharField(max_length=200, verbose_name='商品名')),
                ('description', models.CharField(max_length=400, verbose_name='商品説明')),
                ('weight', models.CharField(blank=True, max_length=200, null=True, verbose_name='重量')),
                ('size', models.CharField(blank=True, max_length=200, null=True, verbose_name='サイズ')),
                ('category', models.ManyToManyField(blank=True, to='jewelstock.category', verbose_name='カテゴリー')),
                ('model_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelstock.modelnumber', verbose_name='形状')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelstock.product', verbose_name='商品'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=jewelstock.models.get_photos_path, verbose_name='画像')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelstock.product')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='開始日')),
                ('due_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='期限')),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='終了日')),
                ('confirmor', models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET('削除されたユーザー'), to=settings.AUTH_USER_MODEL, verbose_name='確認者')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelstock.item', verbose_name='単品')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelstock.process', verbose_name='工程')),
            ],
        ),
        migrations.AddField(
            model_name='modelnumber',
            name='shape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelstock.shape', verbose_name='形状'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(verbose_name='価格')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelstock.item')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelstock.transactionformat', verbose_name='販売形態')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(verbose_name='作成日')),
                ('memo', models.CharField(max_length=500, verbose_name='備考')),
                ('transaction_date', models.DateField(verbose_name='取引日')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelstock.company', verbose_name='取引先')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelstock.transactionformat', verbose_name='販売形態')),
                ('user_name', models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET('削除されたユーザー'), to=settings.AUTH_USER_MODEL, verbose_name='確認者')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelstock.item', verbose_name='単品')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelstock.voucher', verbose_name='伝票')),
            ],
        ),
        migrations.AddField(
            model_name='voucher',
            name='items',
            field=models.ManyToManyField(through='jewelstock.VoucherItem', to='jewelstock.item', verbose_name='単品'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='workplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelstock.workplace', verbose_name='販売店'),
        ),
        migrations.AddField(
            model_name='process',
            name='workplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelstock.workplace', verbose_name='作業所'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_material', models.CharField(max_length=500, verbose_name='注文材料')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='発注日時')),
                ('delivery_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='納品日')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelstock.item')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelstock.workplace', verbose_name='発注場所')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelstock.workplace', verbose_name='作業所')),
            ],
        ),
    ]
