# Generated by Django 5.0.7 on 2024-08-26 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelstock', '0010_rename_workplace_assignment_workplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemExistence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existence', models.BooleanField(default=False, verbose_name='店頭確認')),
                ('confirmed_date', models.DateTimeField(auto_now_add=True, verbose_name='確認日時')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelstock.item', verbose_name='アイテム')),
            ],
        ),
    ]
