# Generated by Django 5.0.7 on 2024-08-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelstock', '0012_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(null=True, to='jewelstock.productcategory', verbose_name='カテゴリー'),
        ),
    ]
