# Generated by Django 5.0.7 on 2024-08-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelstock', '0014_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='jewelstock.productcategory', verbose_name='カテゴリー'),
        ),
    ]
